name: pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: "npm"

      - name: Build
        run: |
          npm ci && npm run build
        env:
          CI: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: percept-site
          path: build
  Deploy-Firebase:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: percept-site
          path: build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERCEPT_E17D2 }}"
          channelId: live
          projectId: percept-e17d2
  Cleanup:
    needs: [Deploy-Firebase]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete build artifacts
        uses: geekyeggo/delete-artifact@v5.0.0
        with:
          name: percept-site
          failOnError: false
